import Head from 'next/head'
import NavBar from '../components/NavBar'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='flex flex-col bg-gray-900 min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className='text-gray-100 p-4'>

        <div className='flex flex-row items-center justify-center text- w-72'>
          <div className='flex flex-col flex-1 w-40'>
            <h1 className='text-7xl'>
              Welcome
            </h1>
            <p className='text-2xl'>This is an example web site that uses NextJs. Here you will find real time data of 4 different cryptocurrencies.</p>
          </div>
        </div>
      </main>
    </div>
  )
}

const load = () => {

}
