import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <nav className='flex flex-row h-16 bg-gray-900 text-gray-200 justify-center items-center'>
          <a>Option 1</a>
          <a>Option 2</a>
          <a>Option 3</a>
          <a>Option 4</a>
        </nav>
      </body>
    </div>
  )
}
