import Head from 'next/head'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div className='flex flex-col bg-gray-900 min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className='text-gray-100'>
        <div className='text-4xl text-center bg-gradient-to-t from-gray-900 to-gray-800 h-16'></div>

        <h1 className='text-7xl text-center mt-6'>
          Welcome
        </h1>

        <div id="graphics" className='flex flex-col p-8'>
          <div className='bg-white rounded-full h-10 w-10 self-end'></div>
          <div className='bg-white rounded-full h-10 w-10 self-center'></div>
          <div className='bg-white rounded-full h-10 w-10'></div>
        </div>
      </main>
    </div>
  )
}
